// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tradekmv/gophermart.git/pkg/accrual (interfaces: ClientInterface)
//
// Generated by this command:
//
//	mockgen -package=mock -destination=pkg/accrual/mock/client.go github.com/tradekmv/gophermart.git/pkg/accrual ClientInterface
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	accrual "github.com/tradekmv/gophermart.git/pkg/accrual"
	gomock "go.uber.org/mock/gomock"
)

// MockClientInterface is a mock of ClientInterface interface.
type MockClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientInterfaceMockRecorder
	isgomock struct{}
}

// MockClientInterfaceMockRecorder is the mock recorder for MockClientInterface.
type MockClientInterfaceMockRecorder struct {
	mock *MockClientInterface
}

// NewMockClientInterface creates a new mock instance.
func NewMockClientInterface(ctrl *gomock.Controller) *MockClientInterface {
	mock := &MockClientInterface{ctrl: ctrl}
	mock.recorder = &MockClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientInterface) EXPECT() *MockClientInterfaceMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockClientInterface) Fetch(ctx context.Context, orderNumber string) (accrual.AccrualInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, orderNumber)
	ret0, _ := ret[0].(accrual.AccrualInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockClientInterfaceMockRecorder) Fetch(ctx, orderNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockClientInterface)(nil).Fetch), ctx, orderNumber)
}
